#!/usr/bin/env node
/* Developer Analytics: real-browser render check for the dashboard.
 *
 * Run:  node test_analytics_ui.js        (needs Google Chrome installed)
 *
 * THE SEAM. The payloads driven through the UI here are not written by hand,
 * they are generated by running the REAL analytics_server.py against accounts
 * built with the REAL fixture helpers in test_analytics_server.py, shaped the
 * way the game client saves them. So the two halves cannot drift apart while
 * both look green on their own: rename a field on the server and this test
 * paints "undefined" and fails.
 *
 * THE DESIGN RULES, AS TESTS. The dashboard's whole point is that it stays
 * simple as it grows, and "keep it clean" is not something a code review
 * reliably catches six months from now. So the limits are asserted:
 *   • Overview shows at most 10 summary cards and exactly 4 blocks
 *   • no page draws more than 4 charts
 *   • the Overview carries no table and at most 3 alerts
 *   • advanced filters start collapsed
 *   • the measure switcher REPLACES its chart instead of adding another
 *   • every card is the same height (consistent card dimensions)
 * plus the things a stubbed document can never catch: a section that renders
 * empty, an "undefined" in visible text, a full-screen overlay that doesn't
 * actually cover the screen, an ✕ that doesn't close it, and a phone-width
 * layout that scrolls sideways. And the jobs it exists for: Lifetime next to
 * the last 30 days, and a list of every player that can be searched and sorted.
 */
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = __dirname;
const CHROME = [
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
].find(p => fs.existsSync(p));

if (!CHROME) {
  console.log("SKIP: no Chrome/Chromium found: cannot run the analytics render check.");
  process.exit(0);
}

const CSS = fs.readFileSync(path.join(ROOT, "multiplayer/client/css/analytics.css"), "utf8");
const MOD = fs.readFileSync(path.join(ROOT, "multiplayer/client/js/analytics-ui.js"), "utf8");

// ── Payloads, straight out of the real server ──────────────────────────────
const PY = `
import json, sys
sys.path.insert(0, ${JSON.stringify(ROOT)})
import analytics_server as an
import test_analytics_server as T

DAY, NOW = 86400, T.NOW

# A fortnight of ordinary play, as the accounts record it: Reef and Kelp most
# days, a couple of games against bots, a team game, both competitive tables,
# and two animals with clearly different fortunes.
games = (
    [T.table(NOW - d * DAY, (("Reef", 50), ("Kelp", 40)),
             boards={"Reef": T.TANG, "Kelp": T.TANG_AND_GOBY},
             strats={"Reef": "King Salmon", "Kelp": "Bait Ball"}) for d in range(1, 13)]
    + [T.table(NOW - d * DAY - 3600, (("Reef", 45), ("Starter Reef", 30))) for d in (2, 5)]
    + [T.table(NOW - 3 * DAY - 5400, (("Reef", 50), ("Kelp", 40), ("Sun", 45), ("Tide", 30)), mode="team")]
    + [T.table(NOW - d * DAY - 7200, (("Reef", 50), ("Kelp", 40), ("Sun", 30)), mode="ranked") for d in (1, 4, 6)]
    + [T.table(NOW - d * DAY - 9000, (("Reef", 60), ("Kelp", 55)), mode="competitive") for d in (2, 7)]
)

class Gen(T.AnalyticsTestCase):
    users = {
        "u-reef": T.account("Reef", games, created=NOW - 120 * DAY, seen=NOW - 600, online=True, older=40,
                            unlocked_icons=["a", "b"], clan_id="c1",
                            stats={"hours_played": 30.5, "level": 18, "critter_coins": 800, "total_xp": 4000,
                                   "strategy_play_counts": {"King Salmon": 30, "Bait Ball": 12},
                                   "most_played_strategy": "King Salmon", "comp_cp": 140,
                                   "lifetime_comp_wins": 4, "lifetime_comp_losses": 1}),
        "u-kelp": T.account("Kelp", games, created=NOW - 100 * DAY, seen=NOW - 3 * DAY,
                            stats={"hours_played": 18.0, "level": 9, "critter_coins": 150, "comp_cp": 60,
                                   "strategy_play_counts": {"Bait Ball": 14},
                                   "lifetime_comp_wins": 1, "lifetime_comp_losses": 4}),
        "u-sun": T.account("Sun", games, created=NOW - 20 * DAY, seen=NOW - DAY,
                           stats={"hours_played": 3.5, "level": 3, "lifetime_comp_losses": 3}),
        "u-sprat": T.account("Sprat", created=NOW - 2 * DAY, seen=NOW - 3600, stats={"level": 1}),
        # Last on 45 days ago: on the list of everyone, not on the game this month.
        "u-gone": T.account("Lapsed", created=NOW - 200 * DAY, seen=NOW - 45 * DAY,
                            stats={"completed_games": 7, "normal_games_by_size": {"2": 7}}),
    }
    extra_store = {
        "clans": {"c1": {"name": "Reefers", "members": {"u-reef": {}, "u-kelp": {}},
                         "seasons": {"2026-Q3": {"points": 40, "games": 9}}, "lifetime": {"points": 40},
                         "created_ts": NOW - 40 * DAY}},
        "trades": {"a__b": {"status": "completed", "completed_ts": NOW - 2 * DAY}},
        "supporters": {"u-reef": {"tier": "Tide"}},
        "supporters/u-reef/payments": {"p1": {"amountCents": 500, "createdAt": NOW - 3 * DAY}},
    }

    def runTest(self):
        pass

g = Gen()
g.setUp()
out = {}
try:
    for name in list(an._SECTIONS) + ["search"]:
        out[name] = g.get(name, days=30, query="Reef")
        out[name + "@0"] = g.get(name, days=0, query="Reef")
    out["live"] = g.get("live")
    # An empty range too, the dashboard has to say "not enough data yet"
    # rather than draw a chart of zeros. No fixture game seats 7.
    out["_empty_overview"] = g.get("overview", days=1, player_count=7)
finally:
    g.tearDown()
print(json.dumps(out))
`;

let PAYLOADS;
try {
  PAYLOADS = JSON.parse(execFileSync("python3", ["-c", PY], {
    encoding: "utf8", maxBuffer: 64 * 1024 * 1024, cwd: ROOT,
  }));
} catch (e) {
  console.log("FAIL: could not generate payloads from analytics_server.py");
  console.log(String(e.stderr || e.message || e));
  process.exit(1);
}

// ── The page ───────────────────────────────────────────────────────────────
const page = `<!doctype html><html><head><meta charset="utf-8">
<style>${CSS}</style>
<style>body{margin:0;font-family:Nunito,sans-serif}</style>
</head><body>
<div class="ph-sidebar-nav"></div>
<div id="RESULT"></div>
<script>
window.__PAYLOADS = ${JSON.stringify(PAYLOADS)};
window.__POSTS = [];
window.__IS_ADMIN = true;
window.__ccAnalytics = {
  APP_BUILD: "test",
  get: async () => ({ ok: true, status: 200, data: { ok: true } }),
  // The REAL bridge resolves to an ENVELOPE: { ok, status, data }, where ok
  // is only the HTTP status. A stub that returns the bare payload would hide
  // the unwrap bug entirely, so it must not.
  post: async (p, b) => {
    window.__POSTS.push({ p: p, b: b });
    const name = p.replace("/api/analytics/", "");
    const data = window.__PAYLOADS[name + "@" + b.days] || window.__PAYLOADS[name]
      || { ok: false, error: "unknown_section" };
    return { ok: true, status: 200, data: data };
  },
  toast: () => {},
  authUser: () => ({ uid: "u1", email: "currentsandcritters@gmail.com" }),
  idToken: async () => "tok",
  isAdmin: () => window.__IS_ADMIN,
};
</script>
<script>${MOD}</script>
<script>
const out = { errors: [], screens: {}, checks: {} };
const BAD = /undefined|NaN|\\[object Object\\]|null/;
const vis = (root) => (root ? (root.innerText || root.textContent || "") : "");
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const inner = () => document.getElementById("ccA-inner");
const lastPost = () => window.__POSTS[window.__POSTS.length - 1] || { b: {} };
const nav = (id) => document.querySelector('.ccA-nav-btn[data-sec="' + id + '"]').click();

async function settle(tries) {
  for (let i = 0; i < (tries || 40); i++) {
    await sleep(50);
    const el = inner();
    if (el && !el.querySelector(".ccA-skel")) return true;
  }
  return false;
}

function survey() {
  const el = inner();
  const text = vis(el);
  const cardEls = [...el.querySelectorAll(".ccA-card")];
  const heights = [...new Set(cardEls.map(c => Math.round(c.getBoundingClientRect().height)))];
  return {
    cards: cardEls.length,
    cardHeights: heights,
    cardLabels: cardEls.map(c => (c.querySelector(".ccA-card-lbl") || {}).textContent || ""),
    charts: el.querySelectorAll(".ccA-chart svg").length,
    panels: el.querySelectorAll(".ccA-panel").length,
    blocks: el.querySelectorAll(".ccA-block").length,
    tables: el.querySelectorAll("table.ccA-table").length,
    alerts: el.querySelectorAll(".ccA-alert").length,
    empties: el.querySelectorAll(".ccA-empty").length,
    noDataCards: [...el.querySelectorAll(".ccA-card-val.ccA-empty")].length,
    legends: el.querySelectorAll(".ccA-legend").length,
    rankRows: el.querySelectorAll(".ccA-rank-row").length,
    tableRows: el.querySelectorAll("table.ccA-table tbody tr").length,
    tooltips: el.querySelectorAll(".ccA-info").length,
    heading: (el.querySelector(".ccA-h1") || {}).textContent || "",
    chip: (el.querySelector(".ccA-range-chip") || {}).textContent || "",
    questions: [...el.querySelectorAll(".ccA-panel-q")].map(q => q.textContent.trim()).filter(Boolean),
    bad: (text.match(BAD) || []).slice(0, 3),
    len: text.length,
  };
}

const playerRows = () => (document.querySelector('.ccA-tbl[data-tbl="players"] .ccA-pager span') || {}).textContent || "";
const firstPlayer = () => ((document.querySelector('.ccA-tbl[data-tbl="players"] tbody tr td') || {}).textContent || "");

(async () => {
  try {
    // 1, a non-admin must get nothing at all.
    window.__IS_ADMIN = false;
    window.__ccAnalyticsOpen();
    out.checks.nonAdminGetsNothing = !document.getElementById("ccA-overlay");
    out.checks.nonAdminMadeNoRequest = window.__POSTS.length === 0;

    // 2: admin opens it.
    window.__IS_ADMIN = true;
    window.__ccAnalyticsOpen();
    await settle();
    const ov = document.getElementById("ccA-overlay");
    const r = ov.getBoundingClientRect();
    out.checks.opens = !!ov && ov.classList.contains("open");
    out.checks.fullScreen = Math.round(r.width) >= window.innerWidth - 1
                         && Math.round(r.height) >= window.innerHeight - 1
                         && Math.round(r.left) === 0 && Math.round(r.top) === 0;
    out.checks.isOpaque = getComputedStyle(ov).backgroundColor !== "rgba(0, 0, 0, 0)";
    const x = document.getElementById("ccA-close");
    const xr = x ? x.getBoundingClientRect() : { width: 0, height: 0 };
    out.checks.hasCloseX = !!x && (x.textContent || "").indexOf("✕") >= 0;
    out.checks.closeXIsClickable = xr.width >= 24 && xr.height >= 24;
    out.checks.advancedCollapsed = !document.getElementById("ccA-adv").classList.contains("open");
    out.checks.filterControls = document.querySelectorAll(".ccA-filters .ccA-ctl").length;
    out.checks.rangeChoices = [...document.querySelectorAll("#ccA-range [data-days]")].map(b => b.textContent.trim());
    out.checks.rangeStartsAt30 = !!document.querySelector('#ccA-range [data-days="30"].on');
    out.checks.bodyScrollLocked = document.body.style.overflow === "hidden";
    out.checks.onlyOneSectionFetched =
      window.__POSTS.filter(p => p.p.indexOf("/api/analytics/") === 0).length === 1;
    out.checks.firstFetchIsOverview =
      (window.__POSTS[0] || {}).p === "/api/analytics/overview";
    out.checks.firstFetchIs30Days = (window.__POSTS[0] || { b: {} }).b.days === 30;
    out.checks.tokenSent = !!(window.__POSTS[0] || {}).b.idToken;

    out.screens.overview = survey();
    // The day still going is dashed, and the top gridline always clears the peak.
    out.checks.partialSegment = document.querySelectorAll("#ccA-inner .ccA-line-partial").length;
    const NT = window.__ccAnalyticsInternals.niceTicks;
    out.checks.ticks43 = NT(43);
    out.checks.ticks5Whole = NT(5, true);
    out.checks.tzSent = typeof (window.__POSTS[0] || { b: {} }).b.tz === "number";

    // 3, the growth switcher must REPLACE the chart, not add a second one.
    const before = document.querySelectorAll("#ccA-inner .ccA-chart svg").length;
    const sw = document.querySelector('[data-switch="growth"] [data-m="cumulative"]');
    if (sw) sw.click();
    await sleep(80);
    out.checks.switcherKeepsChartCount =
      document.querySelectorAll("#ccA-inner .ccA-chart svg").length === before;
    out.checks.switcherMarksItsChoice = !!document.querySelector('[data-switch="growth"] [data-m="cumulative"].on');

    // 4, every other section, one at a time.
    const ids = ["players", "gameplay", "cards", "competitive", "clans",
                 "economy", "events", "technical", "search"];
    for (const id of ids) {
      nav(id);
      await settle();
      out.screens[id] = survey();
    }
    // Only the sections actually visited were ever fetched.
    const fetched = window.__POSTS.map(p => p.p.replace("/api/analytics/", ""));
    out.checks.fetchedOnlyVisited = fetched.every(f => ["overview"].concat(ids).indexOf(f) >= 0);

    // 5: "View details" opens the drawer instead of growing the page.
    nav("gameplay");
    await settle();
    const pageLenBefore = vis(inner()).length;
    const more = document.querySelector('[data-drawer="strategies"]');
    if (more) more.click();
    await sleep(120);
    out.checks.drawerOpens = !!document.querySelector(".ccA-drawer-back");
    out.checks.drawerHasContent = vis(document.querySelector(".ccA-drawer-body")).length > 20;
    out.checks.pageUnchangedByDrawer = vis(inner()).length === pageLenBefore;
    // A table inside the drawer sorts in place, without closing it.
    const drawerSort = document.querySelector('.ccA-drawer [data-sort="strats"][data-key="label"]');
    if (drawerSort) drawerSort.click();
    await sleep(60);
    out.checks.drawerTableSorts = !!document.querySelector('.ccA-drawer [data-key="label"].on')
      && !!document.querySelector(".ccA-drawer-back");
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await sleep(120);
    out.checks.escapeClosesDrawerNotPanel =
      !document.querySelector(".ccA-drawer-back") && ov.classList.contains("open");

    // 6: help drawer carries the definitions.
    document.getElementById("ccA-help").click();
    await sleep(120);
    const help = vis(document.querySelector(".ccA-drawer-body"));
    out.checks.helpHasDefinitions = help.indexOf("Came back after 7 days") >= 0 && help.indexOf("Lifetime") >= 0;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await sleep(80);

    // 7, the player list: who was on the game, everyone, find, sort.
    nav("players");
    await settle();
    out.checks.playersOnTheGame = playerRows();
    document.querySelector('[data-switch="scope"] [data-m="all"]').click();
    await sleep(60);
    out.checks.playersEveryone = playerRows();
    out.checks.playersListTitle = (document.getElementById("ccA-p-list-title") || {}).textContent || "";
    const find = document.getElementById("ccA-p-find");
    find.value = "kel";
    find.dispatchEvent(new Event("input", { bubbles: true }));
    await sleep(60);
    out.checks.playersFound = playerRows() + " / " + firstPlayer();
    out.checks.findKeepsFocusTarget = document.getElementById("ccA-p-find") === find;
    find.value = "";
    find.dispatchEvent(new Event("input", { bubbles: true }));
    await sleep(60);
    const byGames = () => document.querySelector('[data-sort="players"][data-key="games"]');
    byGames().click();
    await sleep(60);
    const topByGames = firstPlayer();
    byGames().click();
    await sleep(60);
    out.checks.sortGamesDesc = topByGames;
    out.checks.sortGamesAsc = firstPlayer();
    out.checks.sortMarksColumn = !!document.querySelector('th[aria-sort] [data-key="games"]');

    // 8, Lifetime: one click, the server is asked for all time, and every
    // section still paints.
    nav("overview");
    await settle();
    document.querySelector('#ccA-range [data-days="0"]').click();
    await settle();
    out.checks.lifetimeRequested = lastPost().p === "/api/analytics/overview" && lastPost().b.days === 0;
    out.checks.lifetimeMarked = !!document.querySelector('#ccA-range [data-days="0"].on');
    out.checks.compareOffForLifetime = document.getElementById("ccA-compare").disabled;
    out.screens.lifetime_overview = survey();
    for (const id of ["players", "gameplay", "cards", "competitive", "clans", "economy", "events"]) {
      nav(id);
      await settle();
      out.screens["lifetime_" + id] = survey();
    }
    out.checks.lifetimePlayersListsEveryone = playerRows();
    nav("players");
    await settle();
    out.checks.lifetimePlayersListsEveryone = playerRows();
    out.checks.lifetimeHasNoScopeSwitch = !document.querySelector('[data-switch="scope"]');
    nav("overview");
    await settle();
    document.querySelector('#ccA-range [data-days="30"]').click();
    await settle();
    out.checks.backTo30 = lastPost().b.days === 30 && !document.getElementById("ccA-compare").disabled;

    // 9, the live tick asks for the live panel alone and swaps it in place.
    window.__PAYLOADS.live = JSON.parse(JSON.stringify(window.__PAYLOADS.live));
    window.__PAYLOADS.live.live.online_players = 42;
    const livePanel = document.getElementById("ccA-live-panel");
    await window.__ccAnalyticsInternals.refreshLive();
    out.checks.liveTickAsksForLive = lastPost().p === "/api/analytics/live";
    out.checks.liveTickSwapsThePanel = document.getElementById("ccA-live-panel") !== livePanel
      && vis(document.getElementById("ccA-live-panel")).indexOf("42") >= 0;

    // 10, an empty range says so instead of drawing zeros. Navigating back is
    // served from cache by design, so this forces a real refetch.
    nav("gameplay");
    await settle();
    const postsBeforeRevisit = window.__POSTS.length;
    window.__PAYLOADS.overview = window.__PAYLOADS._empty_overview;
    nav("overview");
    await settle();
    out.checks.revisitIsServedFromCache = window.__POSTS.length === postsBeforeRevisit;
    document.getElementById("ccA-refresh").click();
    await sleep(200);
    await settle();
    out.checks.refreshAsksForFreshNumbers = lastPost().b.refresh === true;
    const emptySurvey = survey();
    out.screens.emptyOverview = emptySurvey;
    out.checks.emptyRangeSaysSo = emptySurvey.empties > 0 || emptySurvey.noDataCards > 0;
    out.checks.emptyRangeHasNoFakeZeroRate = vis(inner()).indexOf("No data yet") >= 0;

    // 11, the ✕ closes it, and a sign-out closes it too.
    document.getElementById("ccA-close").click();
    await sleep(80);
    out.checks.closesOnX = !ov.classList.contains("open");
    out.checks.bodyScrollRestored = document.body.style.overflow !== "hidden";
    window.__ccAnalyticsOpen();
    await settle();
    window.__IS_ADMIN = false;
    await sleep(2400);   // the admin re-check ticks every 2s
    out.checks.closesOnSignOut = !ov.classList.contains("open");
    window.__IS_ADMIN = true;

    out.viewport = { w: window.innerWidth, h: window.innerHeight };
    out.doc = { scrollW: document.documentElement.scrollWidth };
    out.navVisible = getComputedStyle(document.getElementById("ccA-nav")).display !== "none";
    out.navMobileVisible =
      getComputedStyle(document.querySelector(".ccA-nav-mobile")).display !== "none";

    // Headless Chrome clamps its window to 500px wide, so --window-size=390
    // does NOT give a 390px viewport (it gives 500 and crops the screenshot).
    // Pinning the overlay's width is how a genuinely narrow layout gets tested:
    // walk every element and find anything whose content is wider than the box
    // holding it. The overlay clips with overflow:hidden, so a plain
    // "does the page scroll sideways" check would never see this.
    async function spills() {
      const OK_TO_SCROLL = ["ccA-table-wrap", "ccA-nav", "ccA-body"];
      const found = [];
      ov.querySelectorAll("*").forEach(el => {
        const cls = String(el.className && el.className.baseVal !== undefined
          ? el.className.baseVal : (el.className || ""));
        if (OK_TO_SCROLL.some(c => cls.indexOf(c) >= 0)) return;
        if (el.scrollWidth > el.clientWidth + 1 && el.clientWidth > 0) {
          found.push((el.id || cls || el.tagName) + " " + el.scrollWidth + ">" + el.clientWidth);
        }
      });
      return found;
    }
    window.__ccAnalyticsOpen();
    await settle();
    ov.style.width = "390px";
    window.dispatchEvent(new Event("resize"));
    await sleep(400);
    await settle();
    out.narrowSpills = (await spills()).slice(0, 8);
    out.narrowCards = ov.querySelectorAll(".ccA-card").length;
    // The widest page: the player list, with its switch, its search box and
    // a many-column table.
    nav("players");
    await settle();
    await sleep(250);
    out.narrowPlayerSpills = (await spills()).slice(0, 8);
    ov.style.width = "";
  } catch (e) {
    out.errors.push("THREW: " + (e && e.message ? e.message : String(e)));
  }
  document.getElementById("RESULT").textContent = "@@" + JSON.stringify(out) + "@@";
})();
</script>
</body></html>`;

const file = path.join(os.tmpdir(), `cc_analytics_render_${Date.now()}.html`);
fs.writeFileSync(file, page);

function run(width, height) {
  const dom = execFileSync(CHROME, [
    "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
    `--window-size=${width},${height}`, "--virtual-time-budget=60000",
    "--dump-dom", "file://" + file,
  ], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  const m = dom.match(/@@([\s\S]*?)@@/);
  if (!m) throw new Error("no result payload in the DOM dump");
  return JSON.parse(m[1].replace(/&quot;/g, '"').replace(/&amp;/g, "&")
                        .replace(/&lt;/g, "<").replace(/&gt;/g, ">"));
}

let pass = 0, fail = 0;
const check = (n, c, extra) => {
  if (c) { pass++; console.log("  ✓ " + n); }
  else { fail++; console.log("  ✗ FAIL: " + n + (extra !== undefined ? "  → " + extra : "")); }
};

// ══════════════════════════════════════════════════════════════════════════
console.log("desktop (1440×950):");
const D = run(1440, 950);
check("module ran without errors", D.errors.length === 0, D.errors.join(" | "));

// ── Access + the shell ─────────────────────────────────────────────────────
check("a non-admin gets no dashboard at all", D.checks.nonAdminGetsNothing);
check("a non-admin never even reaches the server", D.checks.nonAdminMadeNoRequest);
check("the admin opens it", D.checks.opens);
check("it covers the entire screen", D.checks.fullScreen);
check("it is opaque (the game behind it never shows through)", D.checks.isOpaque);
check("there is an ✕ to get out of it", D.checks.hasCloseX);
check("the ✕ is a real click target (≥24px)", D.checks.closeXIsClickable);
check("the ✕ closes it", D.checks.closesOnX);
check("closing releases the page scroll", D.checks.bodyScrollRestored);
check("Escape closes the drawer, not the whole dashboard", D.checks.escapeClosesDrawerNotPanel);
check("signing out shuts it", D.checks.closesOnSignOut);
check("every request carries a token", D.checks.tokenSent);

// ── Only the selected section loads ────────────────────────────────────────
check("opening fetches ONE section, not all ten", D.checks.onlyOneSectionFetched);
check("the first section is the Overview", D.checks.firstFetchIsOverview);
check("it opens on the last 30 days", D.checks.firstFetchIs30Days && D.checks.rangeStartsAt30);
check("no section is fetched until it is opened", D.checks.fetchedOnlyVisited);
check("every request says the browser's timezone, so a day is the viewer's day", D.checks.tzSent);
check("the day still in progress is drawn dashed", D.checks.partialSegment >= 2,
      "partial segments=" + D.checks.partialSegment);
check("the top gridline always reaches the biggest value",
      D.checks.ticks43[D.checks.ticks43.length - 1] >= 43, JSON.stringify(D.checks.ticks43));
check("a count gets whole-number gridlines that still reach the top",
      D.checks.ticks5Whole.every(Number.isInteger) && D.checks.ticks5Whole[D.checks.ticks5Whole.length - 1] >= 5,
      JSON.stringify(D.checks.ticks5Whole));

// ── The simplicity rules ───────────────────────────────────────────────────
const ov = D.screens.overview;
check("Overview shows no more than 10 summary cards", ov.cards <= 10, "cards=" + ov.cards);
check("Overview shows exactly 4 blocks", ov.blocks === 4, "blocks=" + ov.blocks);
check("Overview draws no more than 4 charts", ov.charts <= 4, "charts=" + ov.charts);
check("Overview carries no table", ov.tables === 0, "tables=" + ov.tables);
check("Overview shows at most 3 alerts", ov.alerts <= 3, "alerts=" + ov.alerts);
check("every card is the same height, the named ones included", ov.cardHeights.length === 1,
      ov.cardHeights.join(","));
check("the Overview answers how many people are on the game",
      ov.cardLabels.some(l => l.indexOf("Players on the game") === 0), ov.cardLabels.join(" | "));
check("advanced filters start collapsed", D.checks.advancedCollapsed);
check("the main filter bar stays small (≤6 controls)",
      D.checks.filterControls <= 6, "controls=" + D.checks.filterControls);

const SECTIONS = ["overview", "players", "gameplay", "cards", "competitive",
                  "clans", "economy", "events", "technical", "search"];
for (const id of SECTIONS) {
  const s = D.screens[id];
  if (!s) { check(id + ": rendered", false, "missing"); continue; }
  check(id + ": renders real content", s.len > 60, "len=" + s.len);
  check(id + ": draws no more than 4 charts", s.charts <= 4, "charts=" + s.charts);
  check(id + ": no placeholder junk in visible text", s.bad.length === 0, s.bad.join(","));
  check(id + ": has a heading", !!s.heading, s.heading);
}
// The pages that were empty on the live site, with data behind them now.
check("gameplay: the charts have games in them", D.screens.gameplay.charts >= 3,
      "charts=" + D.screens.gameplay.charts);
check("cards: animals, families and oceans are listed",
      D.screens.cards.tableRows >= 2 && D.screens.cards.rankRows >= 5,
      "tableRows=" + D.screens.cards.tableRows + " rankRows=" + D.screens.cards.rankRows);
check("competitive: the two tables are charted", D.screens.competitive.charts >= 1);

// Every chart states the one question it answers.
for (const id of ["overview", "players", "gameplay", "cards", "competitive"]) {
  const qs = D.screens[id].questions;
  check(id + ": every panel says what question it answers",
        qs.length >= 2 && qs.every(q => q.length > 8), JSON.stringify(qs));
}

check("Overview explains its numbers with tooltips, not paragraphs",
      ov.tooltips >= 3, "tooltips=" + ov.tooltips);
check("a single-series chart carries no legend box",
      D.screens.economy.legends === 0, "legends=" + D.screens.economy.legends);
check("a two-series chart DOES carry a legend",
      D.screens.competitive.legends >= 1, "legends=" + D.screens.competitive.legends);

// ── Progressive disclosure ─────────────────────────────────────────────────
check("the measure switcher replaces its chart instead of adding one",
      D.checks.switcherKeepsChartCount);
check("the switcher marks the chosen measure", D.checks.switcherMarksItsChoice);
check("View details opens a drawer", D.checks.drawerOpens);
check("the drawer actually has the detail in it", D.checks.drawerHasContent);
check("opening the drawer doesn't change the page behind it", D.checks.pageUnchangedByDrawer);
check("a table in the drawer sorts without closing it", D.checks.drawerTableSorts);
check("Help carries the definitions, Lifetime included", D.checks.helpHasDefinitions);

// ── Every player ───────────────────────────────────────────────────────────
check("the player list opens on who was on the game", D.checks.playersOnTheGame === "4 rows",
      D.checks.playersOnTheGame);
check("Everyone lists every account", D.checks.playersEveryone === "5 rows", D.checks.playersEveryone);
check("the list says which list it is", D.checks.playersListTitle === "Every player",
      D.checks.playersListTitle);
check("Find a player narrows the list", D.checks.playersFound === "1 row / Kelp", D.checks.playersFound);
check("a column header sorts biggest first", D.checks.sortGamesDesc === "Reef", D.checks.sortGamesDesc);
check("clicking it again sorts the other way", D.checks.sortGamesAsc !== D.checks.sortGamesDesc,
      D.checks.sortGamesAsc);
check("the sorted column is marked for screen readers", D.checks.sortMarksColumn);

// ── Lifetime ───────────────────────────────────────────────────────────────
check("the range offers 7, 30 and 90 days and Lifetime",
      JSON.stringify(D.checks.rangeChoices) === JSON.stringify(["7 days", "30 days", "90 days", "Lifetime"]),
      JSON.stringify(D.checks.rangeChoices));
check("Lifetime is one click, and asks the server for all time", D.checks.lifetimeRequested);
check("the chosen range is marked", D.checks.lifetimeMarked);
check("Compare is switched off for Lifetime", D.checks.compareOffForLifetime);
check("Compare comes back with a date range", D.checks.backTo30);
const life = D.screens.lifetime_overview;
check("Lifetime: the heading says Lifetime", life && life.chip === "Lifetime", life && life.chip);
check("Lifetime: Overview shows hours played", life && life.cardLabels.some(l => l.indexOf("Hours played") === 0),
      life && life.cardLabels.join(" | "));
check("Lifetime: every card is the same height", life && life.cardHeights.length === 1,
      life && life.cardHeights.join(","));
for (const id of ["overview", "players", "gameplay", "cards", "competitive", "clans", "economy", "events"]) {
  const s = D.screens["lifetime_" + id];
  if (!s) { check("lifetime " + id + ": rendered", false, "missing"); continue; }
  check("lifetime " + id + ": renders real content", s.len > 60, "len=" + s.len);
  check("lifetime " + id + ": draws no more than 4 charts", s.charts <= 4, "charts=" + s.charts);
  check("lifetime " + id + ": no placeholder junk", s.bad.length === 0, s.bad.join(","));
}
check("Lifetime: the player list is everyone", D.checks.lifetimePlayersListsEveryone === "5 rows",
      D.checks.lifetimePlayersListsEveryone);
check("Lifetime: there is no 'on the game' switch to confuse it", D.checks.lifetimeHasNoScopeSwitch);

// ── Honesty + cost ─────────────────────────────────────────────────────────
check("the live tick asks for the live panel only", D.checks.liveTickAsksForLive);
check("the live tick updates the panel in place", D.checks.liveTickSwapsThePanel);
check("an empty date range says so instead of charting zeros", D.checks.emptyRangeSaysSo);
check('a rate with no data reads "No data yet", not 0%', D.checks.emptyRangeHasNoFakeZeroRate);
check("going back to a section already loaded costs no request", D.checks.revisitIsServedFromCache);
check("Refresh really does refetch", D.screens.emptyOverview.noDataCards > 0,
      "noDataCards=" + D.screens.emptyOverview.noDataCards);
check("Refresh asks the server for fresh numbers", D.checks.refreshAsksForFreshNumbers);

// ── Layout ─────────────────────────────────────────────────────────────────
check("desktop shows the sidebar nav", D.navVisible);
check("desktop hides the mobile dropdown", !D.navMobileVisible);
check("desktop never scrolls sideways", D.doc.scrollW <= D.viewport.w + 1,
      D.doc.scrollW + " > " + D.viewport.w);

// ══════════════════════════════════════════════════════════════════════════
console.log("\nphone (390×844):");
const M = run(390, 844);
check("module ran without errors", M.errors.length === 0, M.errors.join(" | "));
check("it still covers the entire screen", M.checks.fullScreen);
check("there is still an ✕ to get out of it", M.checks.hasCloseX);
check("the ten tabs become one dropdown", M.navMobileVisible && !M.navVisible);
check("the page never scrolls sideways", M.doc.scrollW <= M.viewport.w + 1,
      M.doc.scrollW + " > " + M.viewport.w);
check("Overview still shows every card", M.screens.overview.cards === D.screens.overview.cards);
check("cards stay a consistent height on a phone",
      M.screens.overview.cardHeights.length === 1, M.screens.overview.cardHeights.join(","));
check("Lifetime still works on a phone", M.checks.lifetimeRequested && M.checks.backTo30);
// Pinned to 390px inside the phone run's viewport, so every phone rule is
// active. (Pinned on the desktop run instead, the sidebar layout was squeezed
// into 390px, and the overlay had been closed by then, so the old version of
// this check measured nothing and could never fail.)
check("nothing spills out of a 390px-wide dashboard",
      (M.narrowSpills || []).length === 0, (M.narrowSpills || []).join(" | "));
check("nothing spills out of the player list at 390px",
      (M.narrowPlayerSpills || []).length === 0, (M.narrowPlayerSpills || []).join(" | "));
check("the cards all survive at 390px", M.narrowCards === M.screens.emptyOverview.cards,
      M.narrowCards + " vs " + M.screens.emptyOverview.cards);
for (const id of SECTIONS) {
  const s = M.screens[id];
  if (s) check(id + ": no placeholder junk on mobile", s.bad.length === 0, s.bad.join(","));
}

// ══════════════════════════════════════════════════════════════════════════
console.log(`\n${pass} passed, ${fail} failed`);
try { fs.unlinkSync(file); } catch (_) {}
process.exit(fail ? 1 : 0);
