#!/usr/bin/env node
/* Developer Analytics: real-browser render check for the dashboard.
 *
 * Run:  node test_analytics_ui.js        (needs Google Chrome installed)
 *
 * THE SEAM. The payloads driven through the UI here are not written by hand,
 * they are generated by running the REAL analytics_server.py against the REAL
 * fixtures in test_analytics_server.py. So the two halves cannot drift apart
 * while both look green on their own: rename a field on the server and this
 * test paints "undefined" and fails.
 *
 * THE DESIGN RULES, AS TESTS. The dashboard's whole point is that it stays
 * simple as it grows, and "keep it clean" is not something a code review
 * reliably catches six months from now. So the limits are asserted:
 *   • Overview shows at most 10 summary cards and exactly 4 blocks
 *   • no page draws more than 4 charts
 *   • the Overview carries no table and at most 3 alerts
 *   • advanced filters start collapsed
 *   • the measure switcher REPLACES its chart instead of adding another
 *   • every card is the same height (consistent card dimensions)
 * plus the things a stubbed document can never catch: a section that renders
 * empty, an "undefined" in visible text, a full-screen overlay that doesn't
 * actually cover the screen, an ✕ that doesn't close it, and a phone-width
 * layout that scrolls sideways.
 */
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = __dirname;
const CHROME = [
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
].find(p => fs.existsSync(p));

if (!CHROME) {
  console.log("SKIP: no Chrome/Chromium found: cannot run the analytics render check.");
  process.exit(0);
}

const CSS = fs.readFileSync(path.join(ROOT, "multiplayer/client/css/analytics.css"), "utf8");
const MOD = fs.readFileSync(path.join(ROOT, "multiplayer/client/js/analytics-ui.js"), "utf8");

// ── Payloads, straight out of the real server ──────────────────────────────
const PY = `
import json, sys, time
sys.path.insert(0, ${JSON.stringify(ROOT)})
import analytics_server as an
import test_analytics_server as T

DAY, NOW = 86400, T.NOW

class Gen(T.AnalyticsTestCase):
    # A fortnight of ordinary activity: completed games, a few abandoned, one
    # ranked match, and two animals with clearly different fortunes.
    games = (
        [T.game(NOW - d * DAY, winner="Reef", names=("Reef", "Kelp"),
                boards=[T._TANG, T._TANG_AND_GOBY], duration=600 + d * 30)
         for d in range(1, 13)]
        + [T.game(NOW - d * DAY, completed=False) for d in (2, 5)]
        + [T.game(NOW - 3 * DAY, team=True, players=4)]
    )
    comp_games = [{
        "room_id": "CCCCC", "recorded_unix": NOW - d * DAY,
        "p1_name": "Reef", "p2_name": "Kelp", "winner": "Reef", "loser": "Kelp",
        "is_draw": False, "forfeit": d == 4, "ranked": True, "turn_count": 12 + d,
    } for d in range(1, 6)]

    def runTest(self):
        pass

g = Gen()
g.setUp()
out = {}
try:
    for name in list(an._SECTIONS) + ["search"]:
        out[name] = g.call(name, days=30, query="Reef").payload
    # An empty range too, the dashboard has to say "not enough data yet"
    # rather than draw a chart of zeros.
    out["_empty_overview"] = g.call("overview", days=1, mode="competitive").payload
finally:
    g.tearDown()
print(json.dumps(out))
`;

let PAYLOADS;
try {
  PAYLOADS = JSON.parse(execFileSync("python3", ["-c", PY], {
    encoding: "utf8", maxBuffer: 64 * 1024 * 1024, cwd: ROOT,
  }));
} catch (e) {
  console.log("FAIL: could not generate payloads from analytics_server.py");
  console.log(String(e.stderr || e.message || e));
  process.exit(1);
}

// ── The page ───────────────────────────────────────────────────────────────
const page = `<!doctype html><html><head><meta charset="utf-8">
<style>${CSS}</style>
<style>body{margin:0;font-family:Nunito,sans-serif}</style>
</head><body>
<div class="ph-sidebar-nav"></div>
<div id="RESULT"></div>
<script>
window.__PAYLOADS = ${JSON.stringify(PAYLOADS)};
window.__POSTS = [];
window.__IS_ADMIN = true;
window.__ccAnalytics = {
  APP_BUILD: "test",
  get: async () => ({ ok: true, status: 200, data: { ok: true } }),
  // The REAL bridge resolves to an ENVELOPE: { ok, status, data }, where ok
  // is only the HTTP status. A stub that returns the bare payload would hide
  // the unwrap bug entirely, so it must not.
  post: async (p, b) => {
    window.__POSTS.push({ p: p, b: b });
    const name = p.replace("/api/analytics/", "");
    const data = window.__PAYLOADS[name] || { ok: false, error: "unknown_section" };
    return { ok: true, status: 200, data: data };
  },
  toast: () => {},
  authUser: () => ({ uid: "u1", email: "currentsandcritters@gmail.com" }),
  idToken: async () => "tok",
  isAdmin: () => window.__IS_ADMIN,
};
</script>
<script>${MOD}</script>
<script>
const out = { errors: [], screens: {}, checks: {} };
const BAD = /undefined|NaN|\\[object Object\\]|null/;
const vis = (root) => (root ? (root.innerText || root.textContent || "") : "");
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

async function settle(tries) {
  for (let i = 0; i < (tries || 40); i++) {
    await sleep(50);
    const inner = document.getElementById("ccA-inner");
    if (inner && !inner.querySelector(".ccA-skel")) return true;
  }
  return false;
}

function survey(id) {
  const ov = document.getElementById("ccA-overlay");
  const inner = document.getElementById("ccA-inner");
  const text = vis(inner);
  const cardEls = [...inner.querySelectorAll(".ccA-card")];
  const heights = [...new Set(cardEls.map(c => Math.round(c.getBoundingClientRect().height)))];
  return {
    cards: cardEls.length,
    cardHeights: heights,
    charts: inner.querySelectorAll(".ccA-chart svg").length,
    panels: inner.querySelectorAll(".ccA-panel").length,
    blocks: inner.querySelectorAll(".ccA-block").length,
    tables: inner.querySelectorAll("table.ccA-table").length,
    alerts: inner.querySelectorAll(".ccA-alert").length,
    empties: inner.querySelectorAll(".ccA-empty").length,
    noDataCards: [...inner.querySelectorAll(".ccA-card-val.ccA-empty")].length,
    legends: inner.querySelectorAll(".ccA-legend").length,
    tooltips: inner.querySelectorAll(".ccA-info").length,
    heading: (inner.querySelector(".ccA-h1") || {}).textContent || "",
    questions: [...inner.querySelectorAll(".ccA-panel-q")].map(q => q.textContent.trim()).filter(Boolean),
    bad: (text.match(BAD) || []).slice(0, 3),
    len: text.length,
  };
}

(async () => {
  try {
    // 1, a non-admin must get nothing at all.
    window.__IS_ADMIN = false;
    window.__ccAnalyticsOpen();
    out.checks.nonAdminGetsNothing = !document.getElementById("ccA-overlay");
    out.checks.nonAdminMadeNoRequest = window.__POSTS.length === 0;

    // 2: admin opens it.
    window.__IS_ADMIN = true;
    window.__ccAnalyticsOpen();
    await settle();
    const ov = document.getElementById("ccA-overlay");
    const r = ov.getBoundingClientRect();
    out.checks.opens = !!ov && ov.classList.contains("open");
    out.checks.fullScreen = Math.round(r.width) >= window.innerWidth - 1
                         && Math.round(r.height) >= window.innerHeight - 1
                         && Math.round(r.left) === 0 && Math.round(r.top) === 0;
    out.checks.isOpaque = getComputedStyle(ov).backgroundColor !== "rgba(0, 0, 0, 0)";
    const x = document.getElementById("ccA-close");
    const xr = x ? x.getBoundingClientRect() : { width: 0, height: 0 };
    out.checks.hasCloseX = !!x && (x.textContent || "").indexOf("✕") >= 0;
    out.checks.closeXIsClickable = xr.width >= 24 && xr.height >= 24;
    out.checks.advancedCollapsed = !document.getElementById("ccA-adv").classList.contains("open");
    out.checks.filterControls = document.querySelectorAll(".ccA-filters .ccA-ctl").length;
    out.checks.bodyScrollLocked = document.body.style.overflow === "hidden";
    out.checks.onlyOneSectionFetched =
      window.__POSTS.filter(p => p.p.indexOf("/api/analytics/") === 0).length === 1;
    out.checks.firstFetchIsOverview =
      (window.__POSTS[0] || {}).p === "/api/analytics/overview";
    out.checks.tokenSent = !!(window.__POSTS[0] || {}).b.idToken;

    out.screens.overview = survey();

    // 3, the growth switcher must REPLACE the chart, not add a second one.
    const before = document.querySelectorAll("#ccA-inner .ccA-chart svg").length;
    const sw = document.querySelector('[data-switch="growth"] [data-m="cumulative"]');
    if (sw) sw.click();
    await sleep(80);
    out.checks.switcherKeepsChartCount =
      document.querySelectorAll("#ccA-inner .ccA-chart svg").length === before;
    out.checks.switcherMarksItsChoice = !!document.querySelector('[data-switch="growth"] [data-m="cumulative"].on');

    // 4, every other section, one at a time.
    const ids = ["players", "gameplay", "cards", "competitive", "clans",
                 "economy", "events", "technical", "search"];
    for (const id of ids) {
      document.querySelector('.ccA-nav-btn[data-sec="' + id + '"]').click();
      await settle();
      out.screens[id] = survey(id);
    }
    // Only the sections actually visited were ever fetched.
    const fetched = window.__POSTS.map(p => p.p.replace("/api/analytics/", ""));
    out.checks.fetchedOnlyVisited = fetched.every(f => ["overview"].concat(ids).indexOf(f) >= 0);

    // 5: "View details" opens the drawer instead of growing the page.
    document.querySelector('.ccA-nav-btn[data-sec="gameplay"]').click();
    await settle();
    const pageLenBefore = vis(document.getElementById("ccA-inner")).length;
    const more = document.querySelector('[data-drawer="strategies"]');
    if (more) more.click();
    await sleep(120);
    out.checks.drawerOpens = !!document.querySelector(".ccA-drawer-back");
    out.checks.drawerHasContent = vis(document.querySelector(".ccA-drawer-body")).length > 20;
    out.checks.pageUnchangedByDrawer =
      vis(document.getElementById("ccA-inner")).length === pageLenBefore;
    const esc = new KeyboardEvent("keydown", { key: "Escape", bubbles: true });
    document.dispatchEvent(esc);
    await sleep(120);
    out.checks.escapeClosesDrawerNotPanel =
      !document.querySelector(".ccA-drawer-back") && ov.classList.contains("open");

    // 6: help drawer carries the definitions.
    document.getElementById("ccA-help").click();
    await sleep(120);
    out.checks.helpHasDefinitions =
      vis(document.querySelector(".ccA-drawer-body")).indexOf("Came back after 7 days") >= 0;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await sleep(80);

    // 7, an empty range says so instead of drawing zeros. Navigating back is
    // served from cache by design, so this forces a real refetch.
    window.__PAYLOADS.overview = window.__PAYLOADS._empty_overview;
    document.querySelector('.ccA-nav-btn[data-sec="overview"]').click();
    await settle();
    out.checks.revisitIsServedFromCache =
      window.__POSTS.filter(p => p.p === "/api/analytics/overview").length === 1;
    document.getElementById("ccA-refresh").click();
    await sleep(200);
    await settle();
    const emptySurvey = survey();
    out.screens.emptyOverview = emptySurvey;
    out.checks.emptyRangeSaysSo =
      emptySurvey.empties > 0 || emptySurvey.noDataCards > 0;
    out.checks.emptyRangeHasNoFakeZeroRate =
      vis(document.getElementById("ccA-inner")).indexOf("No data yet") >= 0;

    // 8, the ✕ closes it, and a sign-out closes it too.
    document.getElementById("ccA-close").click();
    await sleep(80);
    out.checks.closesOnX = !ov.classList.contains("open");
    out.checks.bodyScrollRestored = document.body.style.overflow !== "hidden";
    window.__ccAnalyticsOpen();
    await settle();
    window.__IS_ADMIN = false;
    await sleep(2400);   // the admin re-check ticks every 2s
    out.checks.closesOnSignOut = !ov.classList.contains("open");
    window.__IS_ADMIN = true;

    out.viewport = { w: window.innerWidth, h: window.innerHeight };
    out.doc = { scrollW: document.documentElement.scrollWidth };
    out.navVisible = getComputedStyle(document.getElementById("ccA-nav")).display !== "none";
    out.navMobileVisible =
      getComputedStyle(document.querySelector(".ccA-nav-mobile")).display !== "none";

    // Headless Chrome clamps its window to 500px wide, so --window-size=390
    // does NOT give a 390px viewport (it gives 500 and crops the screenshot).
    // Pinning the overlay's width is how a genuinely narrow layout gets tested:
    // walk every element and find anything whose content is wider than the box
    // holding it. The overlay clips with overflow:hidden, so a plain
    // "does the page scroll sideways" check would never see this.
    ov.style.width = "390px";
    window.dispatchEvent(new Event("resize"));
    await sleep(400);
    await settle();
    const OK_TO_SCROLL = ["ccA-table-wrap", "ccA-nav", "ccA-body"];
    const spills = [];
    ov.querySelectorAll("*").forEach(el => {
      const cls = String(el.className && el.className.baseVal !== undefined
        ? el.className.baseVal : (el.className || ""));
      if (OK_TO_SCROLL.some(c => cls.indexOf(c) >= 0)) return;
      if (el.scrollWidth > el.clientWidth + 1 && el.clientWidth > 0) {
        spills.push((el.id || cls || el.tagName) + " " + el.scrollWidth + ">" + el.clientWidth);
      }
    });
    out.narrowSpills = spills.slice(0, 8);
    out.narrowCards = ov.querySelectorAll(".ccA-card").length;
    ov.style.width = "";
  } catch (e) {
    out.errors.push("THREW: " + (e && e.message ? e.message : String(e)));
  }
  document.getElementById("RESULT").textContent = "@@" + JSON.stringify(out) + "@@";
})();
</script>
</body></html>`;

const file = path.join(os.tmpdir(), `cc_analytics_render_${Date.now()}.html`);
fs.writeFileSync(file, page);

function run(width, height) {
  const dom = execFileSync(CHROME, [
    "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
    `--window-size=${width},${height}`, "--virtual-time-budget=40000",
    "--dump-dom", "file://" + file,
  ], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  const m = dom.match(/@@([\s\S]*?)@@/);
  if (!m) throw new Error("no result payload in the DOM dump");
  return JSON.parse(m[1].replace(/&quot;/g, '"').replace(/&amp;/g, "&")
                        .replace(/&lt;/g, "<").replace(/&gt;/g, ">"));
}

let pass = 0, fail = 0;
const check = (n, c, extra) => {
  if (c) { pass++; console.log("  ✓ " + n); }
  else { fail++; console.log("  ✗ FAIL: " + n + (extra !== undefined ? "  → " + extra : "")); }
};

// ══════════════════════════════════════════════════════════════════════════
console.log("desktop (1440×950):");
const D = run(1440, 950);
check("module ran without errors", D.errors.length === 0, D.errors.join(" | "));

// ── Access + the shell ─────────────────────────────────────────────────────
check("a non-admin gets no dashboard at all", D.checks.nonAdminGetsNothing);
check("a non-admin never even reaches the server", D.checks.nonAdminMadeNoRequest);
check("the admin opens it", D.checks.opens);
check("it covers the entire screen", D.checks.fullScreen);
check("it is opaque (the game behind it never shows through)", D.checks.isOpaque);
check("there is an ✕ to get out of it", D.checks.hasCloseX);
check("the ✕ is a real click target (≥24px)", D.checks.closeXIsClickable);
check("the ✕ closes it", D.checks.closesOnX);
check("closing releases the page scroll", D.checks.bodyScrollRestored);
check("Escape closes the drawer, not the whole dashboard", D.checks.escapeClosesDrawerNotPanel);
check("signing out shuts it", D.checks.closesOnSignOut);
check("every request carries a token", D.checks.tokenSent);

// ── Only the selected section loads ────────────────────────────────────────
check("opening fetches ONE section, not all ten", D.checks.onlyOneSectionFetched,
      "posts=" + D.checks.onlyOneSectionFetched);
check("the first section is the Overview", D.checks.firstFetchIsOverview);
check("no section is fetched until it is opened", D.checks.fetchedOnlyVisited);

// ── The simplicity rules ───────────────────────────────────────────────────
const ov = D.screens.overview;
check("Overview shows no more than 10 summary cards", ov.cards <= 10, "cards=" + ov.cards);
check("Overview shows exactly 4 blocks", ov.blocks === 4, "blocks=" + ov.blocks);
check("Overview draws no more than 4 charts", ov.charts <= 4, "charts=" + ov.charts);
check("Overview carries no table", ov.tables === 0, "tables=" + ov.tables);
check("Overview shows at most 3 alerts", ov.alerts <= 3, "alerts=" + ov.alerts);
check("every card is the same height", ov.cardHeights.length === 1, ov.cardHeights.join(","));
check("advanced filters start collapsed", D.checks.advancedCollapsed);
check("the main filter bar stays small (≤6 controls)",
      D.checks.filterControls <= 6, "controls=" + D.checks.filterControls);

const SECTIONS = ["overview", "players", "gameplay", "cards", "competitive",
                  "clans", "economy", "events", "technical", "search"];
for (const id of SECTIONS) {
  const s = D.screens[id];
  if (!s) { check(id + ": rendered", false, "missing"); continue; }
  check(id + ": renders real content", s.len > 60, "len=" + s.len);
  check(id + ": draws no more than 4 charts", s.charts <= 4, "charts=" + s.charts);
  check(id + ": no placeholder junk in visible text", s.bad.length === 0, s.bad.join(","));
  check(id + ": has a heading", !!s.heading, s.heading);
}

// Every chart states the one question it answers.
for (const id of ["overview", "players", "gameplay", "cards", "competitive"]) {
  const qs = D.screens[id].questions;
  check(id + ": every panel says what question it answers",
        qs.length >= 2 && qs.every(q => q.length > 8), JSON.stringify(qs));
}

check("Overview explains its numbers with tooltips, not paragraphs",
      ov.tooltips >= 3, "tooltips=" + ov.tooltips);
check("a single-series chart carries no legend box",
      D.screens.economy.legends === 0, "legends=" + D.screens.economy.legends);
check("a two-series chart DOES carry a legend",
      D.screens.competitive.legends >= 1, "legends=" + D.screens.competitive.legends);

// ── Progressive disclosure ─────────────────────────────────────────────────
check("the measure switcher replaces its chart instead of adding one",
      D.checks.switcherKeepsChartCount);
check("the switcher marks the chosen measure", D.checks.switcherMarksItsChoice);
check("View details opens a drawer", D.checks.drawerOpens);
check("the drawer actually has the detail in it", D.checks.drawerHasContent);
check("opening the drawer doesn't change the page behind it", D.checks.pageUnchangedByDrawer);
check("Help carries the definitions", D.checks.helpHasDefinitions);

// ── Honesty ────────────────────────────────────────────────────────────────
check("an empty date range says so instead of charting zeros", D.checks.emptyRangeSaysSo);
check('a rate with no data reads "No data yet", not 0%', D.checks.emptyRangeHasNoFakeZeroRate);
check("going back to a section already loaded costs no request",
      D.checks.revisitIsServedFromCache);
check("Refresh really does refetch", D.screens.emptyOverview.noDataCards > 0,
      "noDataCards=" + D.screens.emptyOverview.noDataCards);

// ── Layout ─────────────────────────────────────────────────────────────────
check("desktop shows the sidebar nav", D.navVisible);
check("desktop hides the mobile dropdown", !D.navMobileVisible);
check("desktop never scrolls sideways", D.doc.scrollW <= D.viewport.w + 1,
      D.doc.scrollW + " > " + D.viewport.w);
check("nothing spills out of a 390px-wide dashboard",
      (D.narrowSpills || []).length === 0, (D.narrowSpills || []).join(" | "));
check("the cards all survive at 390px", D.narrowCards === D.screens.emptyOverview.cards,
      D.narrowCards + " vs " + D.screens.emptyOverview.cards);

// ══════════════════════════════════════════════════════════════════════════
console.log("\nphone (390×844):");
const M = run(390, 844);
check("module ran without errors", M.errors.length === 0, M.errors.join(" | "));
check("it still covers the entire screen", M.checks.fullScreen);
check("there is still an ✕ to get out of it", M.checks.hasCloseX);
check("the ten tabs become one dropdown", M.navMobileVisible && !M.navVisible);
check("the page never scrolls sideways", M.doc.scrollW <= M.viewport.w + 1,
      M.doc.scrollW + " > " + M.viewport.w);
check("Overview still shows every card", M.screens.overview.cards === D.screens.overview.cards);
check("cards stay a consistent height on a phone",
      M.screens.overview.cardHeights.length === 1, M.screens.overview.cardHeights.join(","));
for (const id of SECTIONS) {
  const s = M.screens[id];
  if (s) check(id + ": no placeholder junk on mobile", s.bad.length === 0, s.bad.join(","));
}

// ══════════════════════════════════════════════════════════════════════════
console.log(`\n${pass} passed, ${fail} failed`);
try { fs.unlinkSync(file); } catch (_) {}
process.exit(fail ? 1 : 0);
