#!/usr/bin/env node
/* Newsletter admin — real-browser check for /admin/newsletter.
 *
 * Run:  node test_newsletter_admin_ui.js     (needs Google Chrome installed)
 *
 * THE SEAM. The payloads driven through the UI are generated by running the
 * REAL newsletter_server.py against the REAL fixtures in
 * test_newsletter_server.py — not written by hand. Rename a field on the
 * server and this test paints "undefined" and fails, which is the only way to
 * stop the two halves drifting apart while both look green on their own.
 *
 * WHAT IT IS ACTUALLY GUARDING
 *  1. The gate. A non-admin must see a sign-in card and NOTHING else — no
 *     subscriber row, no draft, no count, in the DOM or anywhere else.
 *  2. Escaping. A subscriber address is untrusted text. An address containing
 *     <img onerror> must render as characters, never as an element.
 *  3. The preview iframe is sandboxed with no allow-scripts, so even a
 *     sanitiser bypass cannot execute in the admin's session.
 *  4. The send button is genuinely hard to press by accident: typed phrase,
 *     one-at-a-time, and visually distinct from every other button.
 *  5. It looks right — one card height, no sideways scroll, works at 390px.
 */
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = __dirname;
const CHROME = [
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
].find(p => fs.existsSync(p));

const CSS = fs.readFileSync(path.join(ROOT, "multiplayer/client/css/newsletter.css"), "utf8");
const MOD = fs.readFileSync(path.join(ROOT, "multiplayer/client/js/newsletter-admin.js"), "utf8");
const ADMIN_HTML = fs.readFileSync(path.join(ROOT, "multiplayer/client/newsletter-admin.html"), "utf8");
const UNSUB_HTML = fs.readFileSync(path.join(ROOT, "multiplayer/client/unsubscribe.html"), "utf8");

let pass = 0, fail = 0;
function check(name, ok, detail) {
  if (ok) { pass++; console.log("  ok   " + name); }
  else { fail++; console.log("  FAIL " + name + (detail ? "  — " + detail : "")); }
}

/* ══════════════════════════════════════════════════════════════════════
   PART 1 — static checks that need no browser
   ══════════════════════════════════════════════════════════════════════ */
console.log("\nstatic:");

// The served markup must be an empty shell. What matters is that it carries no
// DATA — no email addresses, no counts, no embedded JSON — not that the word
// "subscribers" never appears (it does, as button copy, which is fine).
{
  const stripped = ADMIN_HTML
    .replace(/fonts\.(googleapis|gstatic)\.com|www\.gstatic\.com/g, "")
    .replace(/currentsandcritters\.com/g, "");
  const addresses = stripped.match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi) || [];
  check("the admin page embeds no email addresses",
        addresses.length === 0, addresses.join(", "));
  check("the admin page embeds no JSON payload",
        !/__PAYLOAD|"subscribers"\s*:|"activeCount"/.test(ADMIN_HTML));
  check("the admin page has no table rows baked in",
        !/<t[dr]\b/i.test(ADMIN_HTML));
}

check("the admin page is marked noindex",
      /name="robots"[^>]*noindex/i.test(ADMIN_HTML));
check("the unsubscribe page is marked noindex",
      /name="robots"[^>]*noindex/i.test(UNSUB_HTML));

check("the admin page loads its JS and CSS with cache-busters",
      /newsletter-admin\.js\?v=/.test(ADMIN_HTML) && /newsletter\.css\?v=/.test(ADMIN_HTML));

check("no inline API secret or key is present in the admin HTML",
      !/(sk_live|sk_test|whsec_|client_secret|refresh_token|AIza)/i.test(ADMIN_HTML));
check("no secret in the admin JS",
      !/(sk_live|sk_test|whsec_|client_secret|refresh_token)/i.test(MOD));

check("the unsubscribe page never echoes the token into the DOM",
      !/innerHTML\s*=\s*[^;]*token/i.test(UNSUB_HTML),
      "the token must not be reflected");
check("the unsubscribe page posts rather than trusting the GET",
      /fetch\(\s*"\/api\/newsletter\/unsubscribe"/.test(UNSUB_HTML) &&
      /method:\s*"POST"/.test(UNSUB_HTML));
check("the unsubscribe page states the required confirmation wording",
      /You have been unsubscribed from the Currents & Critters email list/.test(UNSUB_HTML) &&
      /You will no longer receive newsletter emails from us/.test(UNSUB_HTML));
check("the unsubscribe page carries the business address",
      /Bearded Seal Studios LLC/.test(UNSUB_HTML) &&
      /916A South Douglas Avenue/.test(UNSUB_HTML) &&
      /Nashville, TN 37204-2021/.test(UNSUB_HTML));
check("the unsubscribe page links the Privacy Policy", /href="\/privacy"/.test(UNSUB_HTML));

// ── The Privacy Policy in an email must be the SAME document as the one at the
// bottom of the website. Two different privacy pages is a real legal problem,
// and the drift would be silent: both links keep working, they just stop
// agreeing. So the URL the email footer renders is compared against the href
// the marketing site's footer actually uses.
{
  const SITE = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const siteHrefs = [...new Set((SITE.match(/href="([^"]*privacy[^"]*)"/gi) || [])
    .map(h => h.replace(/^href="|"$/g, "")))];
  check("the website footer links exactly one privacy page",
        siteHrefs.length === 1, siteHrefs.join(", "));

  const emailPrivacy = execFileSync("python3", ["-c", `
import os, re, sys
sys.path.insert(0, ${JSON.stringify(ROOT)})
os.environ.pop("PRIVACY_POLICY_URL", None)
os.environ["CURRENTS_AND_CRITTERS_URL"] = "https://currentsandcritters.com"
import newsletter_email as ne
html = ne.render_email_html(body_html="<p>x</p>", unsubscribe_url="https://x/y")
print(re.findall(r'href="([^"]*)"[^>]*>Privacy Policy<', html)[0])
`], { encoding: "utf8" }).trim();

  const siteAbsolute = "https://currentsandcritters.com" + siteHrefs[0];
  check("the email footer's Privacy Policy is the website's Privacy Policy",
        emailPrivacy === siteAbsolute, emailPrivacy + " vs " + siteAbsolute);

  // Both signup pages must reach it too.
  const JOIN = fs.readFileSync(path.join(ROOT, "multiplayer/client/join.html"), "utf8");
  const CONFIRM = fs.readFileSync(path.join(ROOT, "multiplayer/client/confirm.html"), "utf8");
  check("the join page links the Privacy Policy", /href="\/privacy"/.test(JOIN));
  check("the confirm page links the Privacy Policy", /href="\/privacy"/.test(CONFIRM));

  // Every "Join the Email List" button must reach the real signup, not a form
  // or a mailto — signups anywhere else never become subscribers.
  const m = /EMAIL_LIST_FORM_URL = '([^']*)'/.exec(SITE);
  check("the website's Join-the-Email-List target is set", !!m, "not found");
  check("...and it points at the real signup page",
        !!m && /\/newsletter\/join$/.test(m[1]), m && m[1]);
  check("...not a Google Form or a mailto",
        !!m && !/docs\.google\.com|mailto:/.test(m[1]), m && m[1]);
  const buttons = (SITE.match(/data-email-list/g) || []).length;
  check("every Join-the-Email-List button is wired to that one value",
        buttons >= 4, "found " + buttons);
}

// Server strings must reach the DOM through textContent or the sandboxed
// iframe. There is exactly ONE legitimate exception: restoring a saved draft
// into the contenteditable editor, whose content the server already sanitised
// on save (you cannot edit rich text without assigning markup). Pin it to that
// one line, so a second `innerHTML = <server value>` has to be argued for.
{
  const hits = (MOD.match(/\.innerHTML\s*=\s*[a-zA-Z_$][\w$]*\./g) || []);
  check("only one place assigns server data via innerHTML",
        hits.length === 1, hits.join(" | "));
  check("...and it is the draft editor restore",
        /ed\.innerHTML\s*=\s*d\.campaign\.contentHtml/.test(MOD));
}
check("every table cell is filled with textContent, never innerHTML",
      !/td\.innerHTML|tr\.innerHTML\s*=\s*[a-zA-Z_$]/.test(MOD));
check("the preview iframe is sandboxed with no allow-scripts",
      /setAttribute\("sandbox",\s*""\)/.test(MOD),
      "an empty sandbox attribute denies scripts AND same-origin");
check("the test-send destination is never taken from the page",
      !/test-send[\s\S]{0,400}to:/.test(MOD));

/* ══════════════════════════════════════════════════════════════════════
   The reef on the signup page.

   A critter facing the opposite way to its direction of travel is swimming
   backwards. Nobody can name it, everybody notices it, and it is invisible in
   a diff. Two things are pinned here:

     1. THE RULE — flip exactly when the art's facing disagrees with travel.
     2. THE FACTS — which way each piece of art is drawn. That is a human
        judgement made by looking at the file, so it cannot be re-derived on
        the fly (auto-detecting "which side is the eye on" agrees on 14 of 16
        and confidently gets whale-shark and horned-puffin wrong, because dark
        spots and dark plumage look exactly like a dark eye). Instead every
        avatar's bytes are hashed. Swap the art and this fails, telling you to
        look at the new file and confirm which way it now faces — which is the
        only honest way to catch it.
   ══════════════════════════════════════════════════════════════════════ */
{
  const crypto = require("crypto");
  const JOIN = fs.readFileSync(path.join(ROOT, "multiplayer/client/join.html"), "utf8");
  const PIN = JSON.parse(fs.readFileSync(
    path.join(ROOT, "multiplayer/client/avatar-facing.json"), "utf8"));

  // The table inside the page must agree with the pinned facts.
  const facesRight = new Set([...JOIN.matchAll(/"([a-z-]+)":1/g)].map(m => m[1]));
  const pinnedRight = new Set(Object.keys(PIN).filter(n => PIN[n].faces === "right"));
  check("the page's right-facing list matches the pinned facts",
        [...pinnedRight].every(n => facesRight.has(n)) &&
        [...facesRight].every(n => pinnedRight.has(n)),
        "page=[" + [...facesRight].sort() + "] pinned=[" + [...pinnedRight].sort() + "]");

  // Art must not have silently changed direction under the table.
  let drifted = [];
  for (const [name, info] of Object.entries(PIN)) {
    const f = path.join(ROOT, "multiplayer/client/avatars", name + ".png");
    if (!fs.existsSync(f)) { drifted.push(name + " (missing)"); continue; }
    const sha = crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex").slice(0, 12);
    if (sha !== info.sha) drifted.push(name + " (art changed — RE-CHECK WHICH WAY IT FACES)");
  }
  check("no swimmer's art has changed since its facing was verified",
        drifted.length === 0, drifted.join(", "));

  // Every critter the page asks for actually exists.
  const referenced = [...new Set([...JOIN.matchAll(/\["([a-z-]+)",\s*-?\d/g)].map(m => m[1]))];
  const missing = referenced.filter(n =>
    !fs.existsSync(path.join(ROOT, "multiplayer/client/avatars", n + ".png")));
  check("every critter on the reef has art", missing.length === 0, missing.join(", "));
  check("the reef is populated", referenced.length >= 20, "only " + referenced.length);

  // The rule itself, and the direction each swimmer travels.
  check("the flip is derived from facing vs. travel, not hand-placed",
        /if \(faces\(name\) !== dir\) img\.className = "flip";/.test(JOIN));

  // Work out, for every swimmer, which way it would END UP facing.
  const rows = [...JOIN.matchAll(/\["([a-z-]+)",\s*-?[\d.]+,\s*\d+,\s*\d+,\s*-?[\d.]+,\s*"(left|right)"/g)];
  check("the roster parsed", rows.length >= 14, "parsed " + rows.length);
  const backwards = rows.filter(m => {
    const name = m[1], travels = m[2];
    const art = (PIN[name] || {}).faces || "left";
    const flipped = art !== travels;              // the page's own rule
    const shows = flipped ? (art === "left" ? "right" : "left") : art;
    return shows !== travels;
  }).map(m => m[1]);
  check("no critter swims backwards", backwards.length === 0, backwards.join(", "));

  check("the reef uses the Coral Reef board background",
        /backgrounds\/bg-coral-reef\.png/.test(JOIN));
  check("motion is disabled for prefers-reduced-motion",
        /prefers-reduced-motion: reduce/.test(JOIN) && /animation:none !important/.test(JOIN));
  check("the decoration can never eat a click on the form",
        /\.reef\{[^}]*pointer-events:none/.test(JOIN.replace(/\s+/g, m => m.includes("\n") ? "" : " ")) ||
        /pointer-events:none/.test(JOIN));
}

if (!CHROME) {
  console.log("\nSKIP: no Chrome/Chromium found — skipping the render checks.");
  console.log(`\n${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}

/* ══════════════════════════════════════════════════════════════════════
   PART 2 — payloads out of the REAL server
   ══════════════════════════════════════════════════════════════════════ */
const PY = `
import json, os, sys
sys.path.insert(0, ${JSON.stringify(ROOT)})
os.environ.setdefault("NEWSLETTER_UNSUBSCRIBE_SECRET", "test-secret")
import test_newsletter_server as T
import newsletter_server as ns

case = T.TestCampaigns("test_full_send_one_email_each_no_duplicates")
case.setUp()
try:
    # A realistic list, including one address whose local part is an XSS probe.
    for i in range(4):
        case.signup("p%d@x.com" % i, event_id="e%d" % i, session_id="c%d" % i)
    # A VALID address that still contains characters which MUST be escaped.
    # (An address containing "<" is rejected at signup, so it would never reach
    # the list and would prove nothing about the renderer.)
    case.signup("o'brien&co+<test@x.com", event_id="ex", session_id="cx")
    case.signup("quote'and&amp@x.com", event_id="ex2", session_id="cx2")
    case.admin_post("subscriber-unsubscribe",
                    {"id": ns._subscriber_id("p0@x.com")})
    ns._invalidate_subs_cache()

    cid = case.admin_post("campaign-save", {
        "subject": "Reef Report #1 <script>alert(1)</script>",
        "previewText": "What's new under the waves",
        "contentHtml": "<h2>Big news</h2><p>Hello <b>friends</b></p>"
                       "<ul><li>One</li><li>Two</li></ul>"
                       "<p><a class='cc-btn' href='https://currentsandcritters.com'>Play</a></p>",
    }).last["id"]
    case.admin_post("campaign-start", {"id": cid, "confirm": "SEND"})
    case.run_worker()
    draft = case.admin_post("campaign-save", {
        "subject": "Draft in progress", "contentHtml": "<p>later</p>"}).last["id"]

    out = {
        "dashboard":  case.admin_post("dashboard").last,
        "subscribers": case.admin_post("subscribers", {"perPage": 50}).last,
        "campaign-list": case.admin_post("campaign-list").last,
        "campaign-get": case.admin_post("campaign-get", {"id": draft}).last,
        "campaign-progress": case.admin_post("campaign-progress", {"id": cid}).last,
        "campaign-preview": case.admin_post("campaign-preview", {"id": cid}).last,
        "audit": case.admin_post("audit", {"limit": 50}).last,
        "settings": case.admin_post("settings").last,
        "whoami": case.admin_post("whoami").last,
        "test-send": {"ok": True, "sentTo": T.ADMIN},
        "campaign-save": {"ok": True, "id": draft, "created": False},
        "subscriber-add": {"ok": True, "result": "created"},
        "subscriber-unsubscribe": {"ok": True, "result": "unsubscribed"},
        "campaign-start": {"ok": True, "id": cid, "recipients": 4},
        "export": {"ok": True, "csv": "Email\\n\\"a@b.com\\"", "rows": 1,
                   "filename": "x.csv"},
    }
    out["__progressId"] = cid
finally:
    case.tearDown()
print("@@" + json.dumps(out) + "@@")
`;

let PAYLOADS;
try {
  const raw = execFileSync("python3", ["-c", PY],
                           { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  PAYLOADS = JSON.parse(raw.match(/@@([\s\S]*)@@/)[1]);
} catch (e) {
  console.log("\nFAIL: could not generate payloads from newsletter_server.py");
  console.log(String(e.stdout || e.message).slice(-2500));
  process.exit(1);
}

/* ══════════════════════════════════════════════════════════════════════
   PART 3 — drive the real module in a real browser
   ══════════════════════════════════════════════════════════════════════ */
const BODY = ADMIN_HTML
  .replace(/[\s\S]*<body>/i, "")
  .replace(/<\/body>[\s\S]*/i, "")
  .replace(/<script[^>]*src="[^"]*"[^>]*><\/script>/g, "");

// Inlining JSON into a <script> block: "</" MUST be escaped. The HTML parser
// ends a script at the first literal "</script>" regardless of JSON quoting,
// and these payloads deliberately contain one (the XSS probe in a campaign
// subject). Without this the page silently breaks in half, the rest of the
// payload is parsed as HTML, and the probe's alert(1) runs at page level —
// where headless Chrome blocks forever waiting for a dialog nobody can click.
// The product never does this (it fetches JSON and uses textContent); this is
// purely the test harness needing the same discipline it is testing for.
const inlineJson = obj => JSON.stringify(obj).replace(/<\//g, "<\\/");

const page = `<!doctype html><html><head><meta charset="utf-8">
<style>${CSS}</style>
</head><body>
${BODY}
<div id="RESULT"></div>
<script>
// A dialog in headless Chrome is an infinite hang, so make them impossible.
window.alert = window.confirm = window.prompt = function(){ return null; };
window.__PAYLOADS = ${inlineJson(PAYLOADS)};
window.__POSTS = [];
// Starts DENIED so the very first thing the module does is the rejected path.
// (Flipping it after boot would prove nothing — the module would already have
// been let in.)
window.__ADMIN_OK = false;
window.__FISH_FIREBASE_CONFIG = { apiKey: "fake" };

var USER = {
  email: "timothy.honey@beardedsealstudios.com",
  displayName: "Tim", photoURL: "",
  getIdToken: function(){ return Promise.resolve("tok"); }
};

// Minimal Firebase compat stand-in. Callbacks are COLLECTED, never replaced:
// the module registers its listener at boot, and the test must be able to
// re-fire that same listener later (an earlier version of this stub let the
// test clobber it, so the module never saw the second auth event).
var _authCbs = [];
window.__fireAuth = function(u){
  var user = (u === null) ? null : USER;
  _authCbs.forEach(function(cb){ cb(user); });
};
window.firebase = {
  initializeApp: function(){},
  auth: function(){
    return {
      onAuthStateChanged: function(cb){
        _authCbs.push(cb);
        setTimeout(function(){ cb(USER); }, 0);
      },
      signInWithPopup: function(){ return Promise.resolve({}); },
      signOut: function(){ window.__fireAuth(null); return Promise.resolve(); }
    };
  }
};
window.firebase.auth.GoogleAuthProvider = function(){ this.setCustomParameters = function(){}; };

window.fetch = function(url, opts){
  var body = {};
  try { body = JSON.parse(opts.body); } catch(_) {}
  var action = String(url).replace("/api/newsletter/", "");
  window.__POSTS.push({ action: action, body: body });
  if (!window.__ADMIN_OK) {
    return Promise.resolve({ status: 403, json: function(){
      return Promise.resolve({ ok:false, error:"unauthorized" }); } });
  }
  var data = window.__PAYLOADS[action] || { ok: false, error: "unknown_action" };
  return Promise.resolve({ status: 200, json: function(){ return Promise.resolve(data); } });
};
</script>
<script>${MOD}</script>
<script>
const out = { errors: [], screens: {}, checks: {}, posts: [] };
window.addEventListener("error", e => out.errors.push(String(e.message)));
const BAD = /undefined|NaN|\\[object Object\\]/;
const sleep = ms => new Promise(r => setTimeout(r, ms));
const vis = n => (n ? (n.innerText || n.textContent || "") : "");

function survey() {
  const v = document.getElementById("view");
  const cards = [...v.querySelectorAll(".n-card")];
  return {
    heading: (v.querySelector(".n-h1") || {}).textContent || "",
    cards: cards.length,
    cardHeights: [...new Set(cards.map(c => Math.round(c.getBoundingClientRect().height)))],
    tables: v.querySelectorAll("table.n-table").length,
    rows: v.querySelectorAll("table.n-table tbody tr").length,
    panels: v.querySelectorAll(".n-panel").length,
    empties: v.querySelectorAll(".n-empty").length,
    text: vis(v).slice(0, 4000),
    bad: (vis(v).match(BAD) || []).slice(0, 3),
    len: vis(v).length
  };
}

async function goto(id, wait) {
  const btns = [...document.querySelectorAll(".n-nav-btn")];
  const i = ["dashboard","subscribers","compose","drafts","sent","progress","audit","settings"].indexOf(id);
  btns[i].click();
  await sleep(wait || 320);
  return survey();
}

(async () => {
  try {
    // ── 1. the gate (server says no) ───────────────────────────────
    await sleep(300);
    out.checks.deniedShowsGate = !document.getElementById("gate").classList.contains("n-hidden");
    out.checks.deniedHidesApp = document.getElementById("app").classList.contains("n-hidden");
    out.checks.deniedLeaksNothing =
      !/p1@x\\.com|Reef Report|Active subscribers/i.test(document.body.innerText || "");
    out.checks.deniedSaysWhy = /not authorised/i.test(document.getElementById("gateMsg").textContent);
    out.checks.deniedAskedServer =
      window.__POSTS.some(p => p.action === "whoami");

    // ── 2. admin gets in ───────────────────────────────────────────
    window.__ADMIN_OK = true;
    window.__POSTS.length = 0;
    window.__fireAuth();
    await sleep(600);
    out.checks.appShown = !document.getElementById("app").classList.contains("n-hidden");
    out.checks.gateHidden = document.getElementById("gate").classList.contains("n-hidden");
    out.checks.whoamiShown =
      /timothy\\.honey@beardedsealstudios\\.com/.test(vis(document.getElementById("whoami")));
    out.checks.firstCallIsWhoami =
      window.__POSTS.length > 0 && window.__POSTS[0].action === "whoami";
    out.checks.everyCallCarriesToken =
      window.__POSTS.every(p => p.body && p.body.idToken === "tok");
    out.checks.navCount = document.querySelectorAll(".n-nav-btn").length;
    out.checks.scriptCountBefore = document.querySelectorAll("script").length;

    // ── 3. every section renders ───────────────────────────────────
    for (const id of ["dashboard","subscribers","compose","drafts","sent","progress","audit","settings"]) {
      out.screens[id] = await goto(id, id === "compose" ? 800 : 420);
    }

    // ── 4. escaping ────────────────────────────────────────────────
    await goto("subscribers", 450);
    const v = document.getElementById("view");
    out.checks.scriptCount = document.querySelectorAll("script").length;
    out.checks.ampersandAddressIsText =
      vis(v).indexOf("quote'and&amp@x.com") >= 0;
    out.checks.noStrayElementsFromAddress =
      v.querySelectorAll("img,script,iframe,b").length === 0;

    // ── 5. compose: preview iframe + send guard ────────────────────
    await goto("compose", 900);
    const frame = document.querySelector(".n-preview-frame");
    out.checks.previewIsIframe = !!frame && frame.tagName === "IFRAME";
    out.checks.previewSandboxed = !!frame && frame.getAttribute("sandbox") === "";
    out.checks.previewHasContent = !!frame && (frame.getAttribute("srcdoc") || "").length > 200;
    const tabs = [...document.querySelectorAll(".n-preview-tab")].map(t => t.textContent);
    out.checks.previewTabs = tabs;

    const toolbar = [...document.querySelectorAll(".n-tool")].map(t => t.textContent.trim());
    out.checks.toolbar = toolbar;
    out.checks.editorExists = !!document.getElementById("editor");
    out.checks.editorIsEditable =
      document.getElementById("editor").getAttribute("contenteditable") === "true";

    // Give the composer real content first — every send button refuses to act
    // without a subject, so clicking them empty tests nothing.
    const inputs = [...document.querySelectorAll("#view .n-input")];
    inputs[0].value = "Reef Report #2";
    inputs[0].dispatchEvent(new Event("input", { bubbles: true }));
    document.getElementById("editor").innerHTML = "<p>Hello friends</p>";
    document.getElementById("editor").dispatchEvent(new Event("input", { bubbles: true }));
    await sleep(600);
    out.checks.subjectSet = inputs[0].value;

    // the send button must look different from the save button
    const sendBtn = [...document.querySelectorAll(".n-btn")]
      .find(b => /send to all/i.test(b.textContent));
    const saveBtn = [...document.querySelectorAll(".n-btn")]
      .find(b => /save draft/i.test(b.textContent));
    out.checks.sendIsDistinct = !!sendBtn && !!saveBtn &&
      getComputedStyle(sendBtn).backgroundColor !== getComputedStyle(saveBtn).backgroundColor;
    out.checks.sendIsCoral = !!sendBtn &&
      getComputedStyle(sendBtn).backgroundColor === "rgb(194, 90, 52)";

    // double-clicking Send Test must not fire twice
    window.__POSTS.length = 0;
    const testBtn = [...document.querySelectorAll(".n-btn")]
      .find(b => /send test email/i.test(b.textContent));
    testBtn.click(); testBtn.click(); testBtn.click();
    await sleep(320);
    out.checks.testSendsFired =
      window.__POSTS.filter(p => p.action === "test-send").length;

    // ── 6. the send confirmation ───────────────────────────────────
    window.__POSTS.length = 0;
    sendBtn.click();
    await sleep(700);
    const modal = document.querySelector(".n-modal");
    out.checks.sendOpensModal = !!modal;
    out.checks.modalMentionsCount = !!modal && /Active subscribers/i.test(vis(modal));
    out.checks.modalHasPhraseBox = !!modal && !!modal.querySelector("input");
    out.checks.modalWarnsIrreversible = !!modal && /cannot be undone/i.test(vis(modal));
    out.checks.modalShowsSubject = !!modal && /Subject/i.test(vis(modal));
    out.checks.modalOffersPreview = !!modal && /final preview/i.test(vis(modal));

    // wrong phrase must not start the send
    const okBtn = [...modal.querySelectorAll(".n-btn")].find(b => /send now/i.test(b.textContent));
    modal.querySelector("input").value = "send";
    okBtn.click();
    await sleep(320);
    out.checks.wrongPhraseDoesNotSend =
      window.__POSTS.filter(p => p.action === "campaign-start").length === 0;

    // right phrase does
    modal.querySelector("input").value = "SEND";
    okBtn.click();
    await sleep(420);
    out.checks.rightPhraseSends =
      window.__POSTS.filter(p => p.action === "campaign-start").length === 1;
    out.checks.startCarriedConfirm =
      (window.__POSTS.find(p => p.action === "campaign-start") || {}).body.confirm === "SEND";

    // ── 7. layout ──────────────────────────────────────────────────
    out.viewport = { w: window.innerWidth, h: window.innerHeight };
    out.doc = { scrollW: document.documentElement.scrollWidth };
    out.navVisible = getComputedStyle(document.getElementById("nav")).display !== "none";
    out.navMobileVisible =
      getComputedStyle(document.querySelector(".n-nav-mobile")).display !== "none";
    const spills = [];
    document.querySelectorAll("#app *").forEach(n => {
      const r = n.getBoundingClientRect();
      if (r.width > 0 && r.right > window.innerWidth + 1) {
        spills.push((n.className || n.tagName) + " right=" + Math.round(r.right));
      }
    });
    out.spills = spills.slice(0, 6);
  } catch (e) {
    out.errors.push("THREW: " + (e && e.message) + " @ " + (e && e.stack || "").split("\\n")[1]);
  }
  document.getElementById("RESULT").textContent = "@@" + JSON.stringify(out) + "@@";
})();
</script>
</body></html>`;

const file = path.join(os.tmpdir(), "cc-newsletter-ui-test.html");
fs.writeFileSync(file, page);

function run(width, height) {
  // A hard wall-clock timeout as well as the virtual-time budget. Virtual time
  // fires timers as fast as the CPU allows, so ONE stray setInterval that
  // nothing clears turns "40 virtual seconds" into an infinite loop that never
  // returns. (That is not hypothetical — an early version of the progress
  // poller armed itself after navigation and did exactly this.) Failing in 90
  // real seconds is much better than hanging.
  const dom = execFileSync(CHROME, [
    "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
    `--window-size=${width},${height}`, "--virtual-time-budget=20000",
    // Fail every external request instantly. Chrome PAUSES virtual time while
    // a network request is outstanding, so the email preview's
    // https://currentsandcritters.com/email-logo.png would stall the budget
    // until the socket timed out — which looks exactly like a hang. Blocking
    // the network also means this test can never depend on a live site.
    "--host-resolver-rules=MAP * 127.0.0.1:1",
    "--no-first-run", "--disable-background-networking",
    "--disable-component-update", "--disable-extensions", "--disable-sync",
    "--dump-dom", "file://" + file,
  ], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, timeout: 120000 });
  const m = dom.match(/@@([\s\S]*?)@@/);
  if (!m) throw new Error("no result payload in the DOM dump");
  return JSON.parse(m[1].replace(/&quot;/g, '"').replace(/&amp;/g, "&")
                        .replace(/&lt;/g, "<").replace(/&gt;/g, ">"));
}

const SECTIONS = ["dashboard", "subscribers", "compose", "drafts", "sent",
                  "progress", "audit", "settings"];

console.log("\ndesktop (1440×900):");
const D = run(1440, 900);
check("module ran without errors", D.errors.length === 0, D.errors.join(" | "));

// ── the gate ───────────────────────────────────────────────────────────────
check("a rejected account sees the sign-in gate", D.checks.deniedShowsGate);
check("a rejected account never sees the app", D.checks.deniedHidesApp);
check("a rejected account is shown NO subscriber or newsletter data",
      D.checks.deniedLeaksNothing);
check("a rejected account is told why", D.checks.deniedSaysWhy);
check("the SERVER decides access — the first call is whoami",
      D.checks.firstCallIsWhoami);
check("every API call carries the ID token", D.checks.everyCallCarriesToken);
check("the admin gets in", D.checks.appShown && D.checks.gateHidden);
check("the signed-in account is shown in the header", D.checks.whoamiShown);
check("there are 8 sections", D.checks.navCount === 8, "navCount=" + D.checks.navCount);

// ── every section renders something real ──────────────────────────────────
for (const id of SECTIONS) {
  const s = D.screens[id];
  check(id + ": renders a heading", !!s && s.heading.length > 2, s && s.heading);
  check(id + ": is not blank", !!s && s.len > 60, s && ("len=" + s.len));
  check(id + ": no placeholder junk", !!s && s.bad.length === 0, s && s.bad.join(","));
}
const dash = D.screens.dashboard || { cards: 0, cardHeights: [], text: "", rows: 0 };
check("dashboard shows the counts", dash.cards >= 5, "cards=" + dash.cards);
check("dashboard cards are all the same height",
      dash.cardHeights.length === 1, dash.cardHeights.join(","));
check("subscribers lists the list", (D.screens.subscribers||{rows:0}).rows >= 4,
      "rows=" + (D.screens.subscribers||{rows:0}).rows);
check("subscribers shows active AND unsubscribed counts",
      /Active/.test((D.screens.subscribers||{text:''}).text) &&
      /Unsubscribed/.test((D.screens.subscribers||{text:''}).text));
check("audit shows entries", (D.screens.audit||{rows:0}).rows >= 3, "rows=" + (D.screens.audit||{rows:0}).rows);
check("progress shows a per-status breakdown",
      /Sent/.test((D.screens.progress||{text:''}).text) && /Failed/.test((D.screens.progress||{text:''}).text) &&
      /Skipped/.test((D.screens.progress||{text:''}).text));
check("settings reports how email is sent",
      /Email sending/.test((D.screens.settings||{text:''}).text) &&
      /Method/.test((D.screens.settings||{text:''}).text));
check("settings never claims a From address it did not verify",
      !/Confirmed: this address/.test((D.screens.settings||{text:''}).text) ||
      /Signed in as/.test((D.screens.settings||{text:''}).text));
check("settings reports the Stripe webhook state",
      /Stripe/.test((D.screens.settings||{text:''}).text) && /webhook/i.test((D.screens.settings||{text:''}).text));
check("settings shows which Stripe labels are accepted",
      /Labels we accept/i.test((D.screens.settings||{text:''}).text));

// ── escaping ──────────────────────────────────────────────────────────────
check("an address with & and ' renders as literal text",
      D.checks.ampersandAddressIsText);
check("an address never becomes an element", D.checks.noStrayElementsFromAddress);
check("a <script> in a campaign subject is not parsed into the page",
      D.checks.scriptCount === D.checks.scriptCountBefore,
      D.checks.scriptCountBefore + " -> " + D.checks.scriptCount);
check("the subject with a <script> in it renders as visible text",
      /Reef Report #1/.test((D.screens.sent||{text:""}).text));

// ── composer ──────────────────────────────────────────────────────────────
check("the editor is a rich-text field", D.checks.editorExists && D.checks.editorIsEditable);
for (const t of ["H1", "H2", "B", "I", "U", "• List", "1. List"]) {
  check("toolbar has " + t, D.checks.toolbar.includes(t), D.checks.toolbar.join(" "));
}
check("toolbar can insert a link", D.checks.toolbar.some(t => /Link/.test(t)));
check("toolbar can insert an image", D.checks.toolbar.some(t => /Image/.test(t)));
check("toolbar can insert a styled button", D.checks.toolbar.some(t => /Button/.test(t)));
check("preview offers desktop, mobile and plain text",
      D.checks.previewTabs.join(",") === "Desktop,Mobile,Plain text",
      D.checks.previewTabs.join(","));
check("the preview renders in an iframe", D.checks.previewIsIframe);
check("the preview iframe denies scripts and same-origin", D.checks.previewSandboxed);
check("the preview actually has the rendered email in it", D.checks.previewHasContent);

// ── the dangerous button ──────────────────────────────────────────────────
check("Send-to-all does not look like Save", D.checks.sendIsDistinct);
check("Send-to-all is the one coral button", D.checks.sendIsCoral);
check("triple-clicking Send Test fires exactly one send",
      D.checks.testSendsFired === 1, "fired=" + D.checks.testSendsFired);
check("Send-to-all opens a confirmation", D.checks.sendOpensModal);
check("the confirmation shows the subject", D.checks.modalShowsSubject);
check("the confirmation shows how many people will get it", D.checks.modalMentionsCount);
check("the confirmation offers a final preview", D.checks.modalOffersPreview);
check("the confirmation says it cannot be undone", D.checks.modalWarnsIrreversible);
check("the confirmation demands a typed phrase", D.checks.modalHasPhraseBox);
check("the wrong phrase does not send", D.checks.wrongPhraseDoesNotSend);
check("the right phrase does send", D.checks.rightPhraseSends);
check("the send request carries the confirmation", D.checks.startCarriedConfirm);

// ── layout ────────────────────────────────────────────────────────────────
check("desktop shows the sidebar nav", D.navVisible);
check("desktop hides the mobile dropdown", !D.navMobileVisible);
const Ddoc = D.doc || { scrollW: 0 }, Dvp = D.viewport || { w: 1 };
check("desktop never scrolls sideways", Ddoc.scrollW <= Dvp.w + 1,
      Ddoc.scrollW + " > " + Dvp.w);
check("nothing spills off the right edge", (D.spills || []).length === 0,
      (D.spills || []).join(" | "));

console.log("\nphone (390×844):");
const M = run(390, 844);
check("module ran without errors on mobile", M.errors.length === 0, M.errors.join(" | "));
check("the sidebar becomes one dropdown", M.navMobileVisible && !M.navVisible);
const Mdoc = M.doc || { scrollW: 0 }, Mvp = M.viewport || { w: 1 };
check("the page never scrolls sideways", Mdoc.scrollW <= Mvp.w + 1,
      Mdoc.scrollW + " > " + Mvp.w);
check("nothing spills off the right edge on a phone", (M.spills || []).length === 0,
      (M.spills || []).join(" | "));
check("the dashboard still shows every card",
      (M.screens.dashboard||{}).cards === dash.cards,
      (M.screens.dashboard||{}).cards + " vs " + dash.cards);
check("cards stay a consistent height on a phone",
      ((M.screens.dashboard||{}).cardHeights||[]).length === 1,
      ((M.screens.dashboard||{}).cardHeights||[]).join(","));
for (const id of SECTIONS) {
  const s = M.screens[id];
  if (s) check(id + ": no placeholder junk on mobile", s.bad.length === 0, s.bad.join(","));
}

console.log(`\n${pass} passed, ${fail} failed`);
try { fs.unlinkSync(file); } catch (_) {}
process.exit(fail ? 1 : 0);
